package rules.Validation.TransactionSetValidationRules_dir
uses gw.api.locale.DisplayKey

@gw.rules.RuleName("TXV24000 - Exposure Payment Rules _ Ext")
internal class TXV24000ExposurePaymentRules_Ext {
  static function doCondition(transactionSet     :      entity.TransactionSet) : boolean {
/*start00rule*/
return transactionSet.Subtype == TC_CHECKSET
/*end00rule*/
}

  static function doAction(transactionSet     :      entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*/
 
/*end00rule*/
  }
}
