resources:
  AdminOpenApiSchema:
    permissions:
      view: true
  ClaimApiOpenApiSchema:
    permissions:
      view: true
  CommonOpenApiSchema:
    permissions:
      view: true
  TypeLists:
    permissions:
      view: true
  TypeList:
    permissions:
      view: true