swagger: '2.0'
x-gw-combine:
  - gw.core.cc.common.v1.common_core-1.0
x-gw-schema-import:
  common : gw.content.cc.common.v1.common_content-1.0
produces:
  - application/json
consumes:
  - application/json