swagger: '2.0'
x-gw-combine:
  - gw.content.cc.admin.v1.admin_content-1.0
x-gw-apihandlers:
  - gw.rest.ext.cc.admin.v1.AdminApiExtHandler
x-gw-schema-import:
  common: ext.admin.v1.admin_ext-1.0
produces:
  - application/json
consumes:
  - application/json
paths: {}